patch(lista-estudiantes): se ha agregado lista de estudiantes por asignatura
exdevutem/api-mi-utem pull request #11
Opened 2023-07-26 01:44 UTC by Im-Fran

**ESTA PR DEPENDE DE #6**

Esta PR incluye el endpoint `/v1/asignaturas/:asignaturaId/detalle`. La asignaturaId se puede obtener de `/v1/asignaturas/historicas`, el formato es por ejemplo, álgebra clásica es `MATC8020`. El retorno es un objeto de SeccionAsignatura, el cual contiene un valor 'estudiantes' con la lista de estudiantes

2023-07-26 01:45 UTC, Im-Fran commented
Resuelve #8 y https://github.com/exdevutem/mi-utem/issues/10

2023-08-18 03:20 UTC, mapacheverdugo requested changes
No lo pude probar, imagino que porque falta la otra PR, pero tengo esos comentarios iniciales

2023-08-18 03:20 UTC, mapacheverdugo commented on src/core/routes/asignatura.routes.ts
> +router.post(
Por qué es un POST? Debería ser GET

2023-08-18 03:20 UTC, mapacheverdugo commented on src/core/routes/asignatura.routes.ts
> +  "/asignaturas/:asignaturaId/detalle",
No debería llamarse `:asignaturaId`, quizás `:codigoId` sea lo más correcto, ya que el ID es otra cosa

2023-08-18 13:30 UTC, Im-Fran commented on src/core/routes/asignatura.routes.ts
> +  "/asignaturas/:asignaturaId/detalle",
buen punto, me gusta la idea.

2023-08-18 13:36 UTC, Im-Fran commented on src/core/routes/asignatura.routes.ts
> +router.post(
mas que nada por el uso de las token, estaba pensando a futuro cambiar unas solicitudes get por post, ya que es algo inseguro el enviar tokens mediante las solicitudes get.

2023-08-18 13:37 UTC, Im-Fran commented on src/core/routes/asignatura.routes.ts
> +  "/asignaturas/:asignaturaId/detalle",
Creo que le había puesto asignaturaId porque es lo que vi que usaron de variable en la app xD y ahora veo que es sin el /detalle, así que lo arreglaré también

2023-08-18 13:58 UTC, mapacheverdugo commented on src/core/routes/asignatura.routes.ts
> +router.post(
Más inseguro en base a qué? Porque si bien en los GET quedan expuestos los parametros enviados y en los POST quedan en el body, eso no aplicaría para la token porque en ambos casos se manda en el header

2023-08-18 14:34 UTC, Im-Fran commented on src/core/routes/asignatura.routes.ts
> +router.post(
Realmente por un segundo pense que se enviaba en el cuerpo xDD olvida lo que dije, lo arreglaré xD

2023-08-21 15:30 UTC, Im-Fran commented
@mapacheverdugo acabo de arreglar esto también :)

2023-09-10 03:01 UTC, Im-Fran commented
@mapacheverdugo acabo de arreglar esta PR para usar el nuevo sistema de #6, y agregado una cosa (ya edité el PR con la información).

2023-09-10 21:37 UTC, mapacheverdugo requested changes
Funciona bien, solo un comentario

2023-09-10 21:37 UTC, mapacheverdugo commented on src/mi-utem/services/asignatura.service.ts
> +  public static async getDetalleAsignatura(cookies: Cookie[], codigoAsignatura: string, esLaboratiorio: boolean = false): Promise<SeccionAsignatura> {
Tienes un typo en el parámetro `esLaboratiorio`. Por otro lado, creo que alguna vez vi la existencia de un tercer `tipoHora` que era "TALLER", por lo que yo cambiaría este parámetro a `tipoHora: string = "TEORIA"`

2023-09-11 20:00 UTC, Im-Fran commented on src/mi-utem/services/asignatura.service.ts
> +  public static async getDetalleAsignatura(cookies: Cookie[], codigoAsignatura: string, esLaboratiorio: boolean = false): Promise<SeccionAsignatura> {
ahh buena, incluso mejor idea que el booleano, asi nos preparamos para futuros tipos de hora

2023-09-11 20:00 UTC, Im-Fran commented on src/mi-utem/services/asignatura.service.ts
> +  public static async getDetalleAsignatura(cookies: Cookie[], codigoAsignatura: string, esLaboratiorio: boolean = false): Promise<SeccionAsignatura> {
la implemento en un segundo ;)

2023-09-11 20:09 UTC, Im-Fran commented on src/mi-utem/services/asignatura.service.ts
> +  public static async getDetalleAsignatura(cookies: Cookie[], codigoAsignatura: string, esLaboratiorio: boolean = false): Promise<SeccionAsignatura> {
Listop, acabo de cambiar la variable :p

2023-09-12 00:31 UTC, mapacheverdugo approved these changes

2023-09-12 01:05 UTC, merged