Removido Pupeteer Y Varias Mejoras
exdevutem/api-mi-utem pull request #4
Opened 2023-07-12 01:48 UTC by Im-Fran

# Agregado
* Migrado a NodeJS LTS (actualmente es v18)
* Migrado a Yarn PnP:
> Yarn PnP ofrece una mejora de rendimiento a la hora de inicializar o clonar este repositorio, ya no habrá que esperar más a que npm instale todas las dependencias, yarn de por si incluye en el repositorio todos los archivos necesarios y sus dependencias, solo es necesario ejecutar `yarn install` para generar (si es necesario) el archivo node_modules con sus dependencias requeridas.
* Migrado a docker-compose de dockerfile
> Como ya no es necesario el uso del Dockerfile para instalar yarn he creado el docker-compose.yml. Además esto ofrece una mejora, el volumen del contenedor docker está vinculado a los archivos locales, por lo que si se hace un cambio, ya estará disponible en el contenedor. Además no es necesario construirlo, por lo que es llegar y utilizar `docker compose up -d` y docker descargará las imágenes necesarias.
* Sistema de bypass al SSO:
> El SSO puede ser hecho bypass con el metodo KeycloakUserService#loginSSO
* Agregado .editorconfig y mejoado el tsconfig 

# Removido
* Se ha removido puppeteer por completo lo cual mejorará el rendimiento.
* Se han removido varios métodos marcados como no utilizados (WebStorm mostraba los métodos sin coincidencias de uso)

(Creo que eso es todo lo que he cambiado, probablemente se me van detalles pequeños 😆 )

2023-07-12 01:50 UTC, Im-Fran commented on src/core/controllers/auth.controller.ts
> +            let usuarioMiUtem: Usuario// = await MiUtemUserService.getProfile(cookies)
Realmente no tengo idea si es necesario o no el uso del usuarioMiUtem, si se agrega ahora tarda 13 segundos cada solicitud, pero incluye la fotoUrl, que creo que es lo único utilizado acá

2023-07-12 01:52 UTC, Im-Fran commented on src/core/controllers/auth.controller.ts
> +            let usuarioMiUtem: Usuario// = await MiUtemUserService.getProfile(cookies)
Ah, y también las cookies del CreentialUtils, quizás se pueda agregar como otra solicitud a parte la solicitud del token, para reducir el tiempo de espera al login y obtención de datos del MiUTEM.

2023-07-18 01:36 UTC, mapacheverdugo commented
Primera PR externa, que bonito! 🥳  Ahora reviso esto, no sé cuánto me demore que está cuatico

2023-07-18 02:30 UTC, mapacheverdugo commented
@Im-Fran, los nuevos tiempos de respuesta son mucho mejores que antes, así que ta de pana!

Ahora, me surge una duda porque me pierdo con el proceso de auth, existe algún valor/cookie/credencial que podamos guardar como token para ahorrarnos el proceso de auth cada vez? Porque ese proceso es como la mitad del tiempo de la respuesta de los permisos (Pero igual hay que asegurarse que valga la pena, porque si hay que refrescarla a cada rato con el mismo proceso, no vale la pena)

De todas formas, creo que estos cambios por sí solos tienen el valor suficiente para incorporarlos, seguiré revisando a ver si encuentro algún detalle

2023-07-18 02:31 UTC, mapacheverdugo commented on src/core/controllers/auth.controller.ts
> +            let usuarioMiUtem: Usuario// = await MiUtemUserService.getProfile(cookies)
> Ah, y también las cookies del CreentialUtils, quizás se pueda agregar como otra solicitud a parte la solicitud del token, para reducir el tiempo de espera al login y obtención de datos del MiUTEM.

Creo que esto es lo que te preguntaba en el hilo principal, no? No me queda claro como sería, y cuánto duraría esa credencial

2023-07-18 02:58 UTC, mapacheverdugo requested changes
Hay algunos detalles. Y me gustaría si podemos no modificar el indent y dejar afuera lo de yarn zero-install ignorando todos esos archivos por ahora para revisar mejor los cambios, crees que sea muy complejo de hacer?

Podríamos dejar esos cambios para otro PR en caso de ser necesario

2023-07-18 02:58 UTC, mapacheverdugo commented on .editorconfig
> +indent_size = 4
Muchos de los cambios tienen que ver con esto, creo que deberíamos dejar 2, basándome en [esta guía](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#spaces), tú tienes alguna razón para dejarlo de 4?

2023-07-18 02:58 UTC, mapacheverdugo commented on src/mi-utem/services/asignatura.service.ts
Por qué se eliminó este archivo?

2023-07-18 03:19 UTC, Im-Fran commented on .editorconfig
> +indent_size = 4
Mas que nada es para no tener demasiada acumulación visual, creo que ya me acostumbré porque los IDEs de JetBrains usan 4 por defecto, pero claro, se puede dejar en 2 😛

2023-07-18 03:21 UTC, Im-Fran commented on src/mi-utem/services/asignatura.service.ts
Es un archivo "duplicado" por decirlo de una forma, el mismo método ya lo había reparado en nota.service.ts, y retornaban los mismos valores, olvidé mencionarlo 😅

2023-07-18 03:28 UTC, Im-Fran commented on src/core/controllers/auth.controller.ts
> +            let usuarioMiUtem: Usuario// = await MiUtemUserService.getProfile(cookies)
Sip, eso mismo, si no me equivoco las cookies duran 12-18 horas, no lo he probado muy bien.

2023-07-18 03:31 UTC, Im-Fran commented
> Ahora, me surge una duda porque me pierdo con el proceso de auth, existe algún valor/cookie/credencial que podamos guardar como token para ahorrarnos el proceso de auth cada vez? Porque ese proceso es como la mitad del tiempo de la respuesta de los permisos (Pero igual hay que asegurarse que valga la pena, porque si hay que refrescarla a cada rato con el mismo proceso, no vale la pena)

@mapacheverdugo sip, eso mismo que te respondí en la conversa de auth.controller.ts, las cookies que estan comentadas son las que pueden ser guardadas en el bearer token que se usa más tarde, la cosa es que la primera solicitud siempre serán aprox 13 segundos, por lo que pensaba que hay 2 opciones:

* Hacerlas una solicitud aparte cosa de poder refrescarlas cada por ejemplo 6 horas en la actividad background de la app de los estudiantes
* Solo realizarla al inicio, cosa de que cada que se inicia la app se hace el login, pero ahí puede ralentizar el proceso de inicio de la app.

Aunque ahora que lo pienso podrían ser ambas, tipo al inicio del login se te pide una sola vez, guardas la credencial (usuario y clave) y luego cada cierto tiempo se refrescan los datos

2023-07-18 03:32 UTC, Im-Fran commented
> Hay algunos detalles. Y me gustaría si podemos no modificar el indent y dejar afuera lo de yarn zero-install ignorando todos esos archivos por ahora para revisar mejor los cambios, crees que sea muy complejo de hacer?
> 
> Podríamos dejar esos cambios para otro PR en caso de ser necesario

No para nada, puedo hacerlo ahora mismo, por suerte yarn ofrece una opción para ello jaja, lo pondré en modo `node_modules` para que elimine los archivos .zip y ya en otra PR los puedo agregar.

2023-07-18 03:41 UTC, Im-Fran commented
Oh wait, aun mejor, existe la opción de usar yarn pnp sin node_modules xD (la idea principal del pnp acá era reducir el uso del I/O del disco, lo cual es resuelto por yarn pnp), solo desactivaré el cache, pero igual será necesario usar `yarn install` entre cada actualización para regenerar el cache.

2023-07-18 03:47 UTC, Im-Fran commented on src/mi-utem/services/asignatura.service.ts
En realidad ahora que lo veo, creo que me salté el método del detalle de la asignatura, lo agrego en breve :wink:

2023-07-18 04:23 UTC, Im-Fran commented
lol, me demoré 34 minutos, pensé que tardaría mas. 

En fin, acabo de agregar el servicio de asignatura, ahora que lo vi nuevamente lo había borrado porque no hay referencias a los usos de los métodos desde otros archivos en todo el proyecto. Pero en caso de ser necesario ahí esta disponible.

En teoría debe de funcionar, igualmente hay que testear pero debe de funcionar.

2023-07-18 04:26 UTC, Im-Fran commented on src/core/controllers/auth.controller.ts
> +            let usuarioMiUtem: Usuario// = await MiUtemUserService.getProfile(cookies)
Acabo de quitar el comentario, aunque tarde 13 segundos extra, ya no hace falta el login en cada endpoint, se puede usar el  bearer token que ya fue configurado para los otros endpoints.

2023-07-18 04:28 UTC, Im-Fran commented
creo que ya resolví todos los comentarios xD

2023-07-19 14:17 UTC, mapacheverdugo commented
@Im-Fran Ya revisé todo, se ve bien, pero tengo un problema para subir esto al servidor, no se está haciendo el deploy correcto a DigitalOcean App Platform y el error que entrega no es muy descriptivo. Hay alguna razón para reemplazar el Dockerfile y no adaptarlo?

2023-07-19 14:25 UTC, Im-Fran commented
Sip, había visto cuando agregaron el Dockerfile en un comentario que tambien querían utilizar docker-compose, lo agregaré nuevamente para que esté adaptado :wink:

2023-07-20 02:14 UTC, Im-Fran commented
@mapacheverdugo lamento el retraso, acabo de subirlos xD 

Estuve toda la tarde configurando mi compu windows para hacer esto, pero me aburrí y lo hice en la mac 🤣

2023-07-20 02:20 UTC, Im-Fran commented
Lo que si no he testeado es el sistema de guardado del token, que al inicio de sesión te devuelve un token que se puede utilizar como bearer token y sus headers en otras solicitudes

2023-07-20 03:39 UTC, mapacheverdugo approved these changes
Ahora funciona bien!

2023-07-20 23:50 UTC, PollitoMayo approved these changes

2023-07-21 00:06 UTC, merged