patch(bearer-token): se ha agregado y mejorado el sistema de token
exdevutem/api-mi-utem pull request #6
Opened 2023-07-22 03:11 UTC by Im-Fran

He mejorado el sistema de Bearer token al agregar un sistema más seguro de obtener un buen resultado válido al decodificar las tokens. El nuevo formato es `base64(expira|sessionid|csrftoken)|sigatoken`. Esto nos dará un sistema con una duración de las cookies de miutem de 6 horas.

Esto además mejora el tiempo de carga de los permisos de ser de los actuales 16 segundos aprox., a 6 segundos con las cookies guardadas. Lo mismo ocurrirá con las asignaturas históricas, de ser 16 segundos pasa a 6.

Por último se han hecho mejoras a:
- Login keycloak utiliza el método header de Cookie#header
- Validación de cookies en MiUtemAuthService
- CredentialsUtils ahora retorna un array de Cookies en lugar de un objeto
- Reparado un error que no guardaba el valor en bruto de una cookie al ser iniciada con su constructor.
- Validación extra en el CredentialsMiddleware en caso de retornar cookies vacías

2023-08-17 15:41 UTC, Im-Fran commented
Reabrí esta PR porque sin querer en GitHub presioné 'descartar commits' y se eliminaron xD

2023-08-17 15:42 UTC, Im-Fran commented
@mapacheverdugo me gustaría que porfis revises esta PR que creo que es la más importante, ya que nos abre las puertas a nuevas características de la API, como sería para la PR #9 

Además pronto agregaré un endpoint para solicitar y ver certificados por ejemplo de alumno regular, etc.

2023-08-17 16:12 UTC, mapacheverdugo commented
Hoy me comprometo a revisar todoooo. Igual hace poco se hizo un fix fast-track, así que ve si tienes que actualizar tus PRs

2023-08-17 17:53 UTC, Im-Fran commented
Sip, ya estan todas actualizadas :laughing: gracias.

2023-08-18 02:44 UTC, mapacheverdugo requested changes

2023-08-18 02:44 UTC, mapacheverdugo commented on src/mi-utem/services/auth.service.ts
> +          Cookie: Cookie.header(Cookie.merge(miutemBaseCookies, cookies)),
Hay un error acá en la llamada al merge

2023-08-18 02:44 UTC, mapacheverdugo commented on src/infrastructure/models/cookie.model.ts
>      if (!original) return other;
Quedo esta línea, del merge asumo

2023-08-18 13:26 UTC, Im-Fran commented on src/infrastructure/models/cookie.model.ts
>      if (!original) return other;
hmm, debería de funcionar de cualquier forma xD lo arreglaré

2023-08-20 14:15 UTC, mapacheverdugo commented
@Im-Fran etiquetame cuando este listo para revisar

2023-08-21 15:22 UTC, Im-Fran commented
@mapacheverdugo olvidé hacerle push xDD listop :stuck_out_tongue:

2023-08-23 04:48 UTC, mapacheverdugo reviewed
Varias cositas, no pude terminar de probarlo porque me sale el error `ReferenceError: btoa is not defined`

2023-08-23 04:48 UTC, mapacheverdugo commented on src/core/controllers/auth.controller.ts
> +      const academiaCookies = await AcademiaUserService.loginAndGetCookies(correo, contrasenia)
Esta función debería ir debajo de la token de SIGA, creo que la principal es la de SIGA, y el resto que vaya después

2023-08-23 04:48 UTC, mapacheverdugo commented on src/core/controllers/auth.controller.ts
> +      const academiaCookies = await AcademiaUserService.loginAndGetCookies(correo, contrasenia)
También deberías seguir la misma estructura que se hizo con las `cookies` de Mi UTEM, con su try-catch y que queden nulleables en caso de error

2023-08-23 04:48 UTC, mapacheverdugo commented on src/core/controllers/auth.controller.ts
> +      const academiaCookies = await AcademiaUserService.loginAndGetCookies(correo, contrasenia)
Por otro lado, ya que se agregó otra "cookies" a la función, la variable `cookies` que ya estaba en el código debería cambiarse a `miUtemCookies` por consistencia de naming

2023-08-23 04:48 UTC, mapacheverdugo commented on src/infrastructure/utils/credentials.utils.ts
> +    const miutemToken = btoa(`${expira}|${miUtemCookies.map(it => btoa(it.raw)).join('|')}`)
Esto considera que `miUtemCookies` y `academiaCookies` pueda ser null? En el caso de que fallen

2023-08-23 04:48 UTC, mapacheverdugo commented on src/infrastructure/utils/credentials.utils.ts
> +    const academiaToken = btoa(`${expira}|${academiaCookies.map(it => btoa(it.raw)).join('|')}`)
Cuando corro la función me arroja el error `ReferenceError: btoa is not defined`

2023-08-23 04:48 UTC, mapacheverdugo commented on src/core/controllers/auth.controller.ts
> +      const usuario: Usuario = {...usuarioSiga, ...usuarioToken};
La aplicación no corre porque se cambió de `let` a `const` y luego se intenta reasignar, hay que volver a dejarlo en `let`

2023-08-24 15:22 UTC, Im-Fran commented
xD creo que nunca ví los errores que trajo el merge, arreglaré todo en unos minutos ;)

2023-08-26 16:48 UTC, Im-Fran commented
@mapacheverdugo resolví todos los errores.

Sobre el btoa no existe sinceramente no se por que no te funciona... como ejecutas el backend?

2023-08-26 16:55 UTC, Im-Fran commented
Yo al utilizar docker funciona perfecto :p intenta usando `docker compose up -d`

2023-08-28 02:58 UTC, mapacheverdugo commented
@Im-Fran Pucha, sigue sin funcionarme bien, Academia falla al obtener el perfil (supongo que será algo de la cuenta que estoy probando así que pensaba dejarlo pasar). El tema es que si falla Academia o Mi UTEM, esa sección de la token se genera como `Mon Aug 28 2023 08:34:27 GMT+0000 (Coordinated Universal Time)|` encodeado, a pesar de no tener ningún valor útil como cookie.

Luego, en las funcionas de `getMiUtemCookies` o `getAcademiaCookies` no se valida ese caso y se intenta crear una instancia de `Cookie` inválida, solo con `expires`. Si bien este problema se podría solucionar si modificamos la función `createToken` para que genera los segmentos vacíos (como string vacío) en caso de error, igual está el problema del middleware donde se valida que las 3 tokens existan.

Creo yo que la solución sería crear un middleware para cada servicio, uno para SIGA (el que ya estaba), uno para Academia y otro para Mi UTEM, y que cada uno sea independiente entre sí sin importarle si las otras tokens están definidas o no.

Por cierto, desde `docker compose up -d` efectivamente no tira error el `btoa`. Igual creo que es algo a corregir que funcione desde `yarn start-dev` porque no me gusta desarrollar teniendo que ocupar Docker, pero pensaba que podíamos dejarlo pasar dado el valor que tiene esta PR

2023-08-28 15:52 UTC, Im-Fran commented
Que version de nodejs usas? quizás es eso xD revisa que tengas la ultima lts, creo que era la 18.16 o 18.17

2023-08-28 15:57 UTC, Im-Fran commented
además si, me gusta tu idea de tener distintos middleware para las token requeridas, agregaré eso más tarde cuando llegue a casa.

Y sobre academia, estás utilizando tu cuenta personal o tienes una de prueba? De cualquier forma lo revisaré 😄

2023-08-30 01:43 UTC, mapacheverdugo commented
> Y sobre academia, estás utilizando tu cuenta personal o tienes una de prueba? De cualquier forma lo revisaré 😄

Estoy usando la personal de otro de los chicos del club xd Porque yo ya no tengo carreras activas

2023-09-03 02:02 UTC, Im-Fran commented
@mapacheverdugo acabo de hacer un push que agrega lo que indicaste de separar los middlware, además agregué el login usando /pasaporte/ que mientras la página esté activa, sirve MUCHO más rápido, medí aprox 2.6 a 3 segundos de login completo, saltandose la página principal xD

2023-09-03 02:08 UTC, mapacheverdugo commented
Me pillaste desocupado, lo reviso al toque

2023-09-04 03:00 UTC, mapacheverdugo requested changes
Casi casi, pero sigue sin funcionarme, corrigiendo esas cositas ya estaríamos listos para mergear. Lo siento pedirte tantos cambios xd

2023-09-04 03:00 UTC, mapacheverdugo commented on src/infrastructure/middlewares/credentials/miutem-credentials.middleware.ts
> +      let [error, accessToken] = this.validateToken(req)
Si pongo `this.validateToken` me tira error, pero si lo reemplazo por `MiUTEMCredentialsMiddleware.validateToken` me funciona

2023-09-04 03:00 UTC, mapacheverdugo commented on src/infrastructure/middlewares/credentials/academia-credentials.middleware.ts
> +      let [error, accessToken] = this.validateToken(req)
Si pongo `this.validateToken` me tira error, pero si lo reemplazo por `AcademiaCredentialsMiddleware.validateToken` me funciona

2023-09-04 03:00 UTC, mapacheverdugo commented on src/infrastructure/middlewares/credentials/academia-credentials.middleware.ts
> +        return next(accessToken)
Acá no funciona que pongas un `next` pero envies un dato que no es una `Exception` porque eso hace que el endpoint se ejecute actualmente sin setear el `academiaCookies`. Lo mejor es poner directo un `throw` para que caiga en el `next` del `catch`, o poner un next con una excepción

2023-09-04 03:00 UTC, mapacheverdugo commented on src/infrastructure/middlewares/credentials/miutem-credentials.middleware.ts
> +        return next(accessToken)
Acá no funciona que pongas un `next` pero envies un dato que no es una `Exception` porque eso hace que el endpoint se ejecute actualmente sin setear el `miUtemCookies`. Lo mejor es poner directo un `throw` para que caiga en el `next` del `catch`, o poner un next con una excepción

2023-09-04 03:00 UTC, mapacheverdugo commented on src/infrastructure/middlewares/credentials/siga-credentials.middleware.ts
> +        return next(accessToken)
Acá no funciona que pongas un `next` pero envies un dato que no es una `Exception` porque eso hace que el endpoint se ejecute actualmente sin setear el `sigaToken` ni `sigaUser`. Lo mejor es poner directo un `throw` para que caiga en el `next` del `catch`, o poner un `next` con una excepción

2023-09-04 12:35 UTC, Im-Fran commented
Jaja, no había notado que me salté el `return next(accessToken)`, tienes razón, ahí iba un `return next(error)`

Y realmente ni siquiera me saltó error al usar this.validateToken, deben ser realmente las versiones, pero ya lo arreglé.

2023-09-04 12:35 UTC, Im-Fran commented
@mapacheverdugo todo listo entonces, a menos que encuentres algo más xDD

2023-09-04 13:16 UTC, mapacheverdugo approved these changes

2023-09-04 13:17 UTC, Im-Fran commented
Nicee

2023-09-08 13:02 UTC, merged