feat(codigo-beca-alimentacion): agregado codigo para beca de alimenta…
exdevutem/api-mi-utem pull request #9
Opened 2023-07-26 00:41 UTC by Im-Fran

…ción

Parte de una de las varias actualizaciones para el uso de la Academia.UTEM, esto permite realizar una solicitud POST a `/v1/academia/beca_alimentacion` para obtener un código con el formato `{"codigo":"XXXXXXXXXX"}`, lo que permitirá generar dentro de la app el codigo de la beca de alimentación UTEM.

**ESTA PR DEPENDE DE #6**
Mas que nada por el sistema de tokens mejorado y arreglado (incluyendo la token de la academia)

2023-08-18 03:32 UTC, mapacheverdugo commented
Academia no entrega más información? Sería bueno traer toda la info que exista

Por otro lado no tengo cuenta con beca de alimentación (de hecho ya no tengo cuenta con asignaturas xd), crees que puedas mandar tus credenciales por interno para probar cuando esté lista #6?

2023-08-18 13:38 UTC, Im-Fran commented
Claro, no hay problema! Y sip, entrega más info, pensaba en dedicar una PR para cada tipo de información para no hacer PRs tan grandes, por ahora solo se me ocurrió lo del código de alimentación 😆

2023-08-18 13:39 UTC, Im-Fran commented
te envio un correo, mensaje por twitter, discord, que prefieres?

2023-08-18 13:39 UTC, Im-Fran commented
te envio un correo, mensaje por twitter, discord, que prefieres?

2023-09-10 01:53 UTC, Im-Fran commented
@mapacheverdugo acabo de pensar en algunas cosas, y además contarte que:

1. Nop, lo unico que sería de datos para traer de academia es eso, lo otro podría ser los datos de sesaes de horas médicas. Ni idea como funciona pero si alguien con una cuenta que tenga datos de sesaes (https://academia.utem.cl/sesaes/anular solo html basta) podría ver que datos sacar y como hacerlo.

2. En #6 me decías que tenias datos faltantes de academia, creo que es porque te faltaban unas cosas en tu .env:
`ACADEMIA_UTEM_URL=https://academia.utem.cl` y `ACADEMIA_CLIENT_SECRET=....`. El secret lo obtienes con un CURL a `https://academia.utem.cl/sso`, no lo voy a subir/postear para evitar leaks de datos. (En la variable keycloack está)

3. Necesito que me digas como prefieres que te envíe los datos xDD

2023-09-10 03:05 UTC, Im-Fran commented
igual creo que por ahora está bien solo esto, lo de sesaes se puede hacer en otra PR para no agregar tanto dentro de esta misma PR.

2023-09-10 21:44 UTC, mapacheverdugo commented
> En https://github.com/exdevutem/api-mi-utem/pull/6 me decías que tenias datos faltantes de academia, creo que es porque te faltaban unas cosas en tu .env:
ACADEMIA_UTEM_URL=https://academia.utem.cl y ACADEMIA_CLIENT_SECRET=..... El secret lo obtienes con un CURL a https://academia.utem.cl/sso, no lo voy a subir/postear para evitar leaks de datos. (En la variable keycloack está)

Ya tenía esas variables de entorno y me sigue sin funcionar :( Pero si me pasarás tus credenciales puedo descartar si es la cuenta con la que estoy probando u otra cosa

> Necesito que me digas como prefieres que te envíe los datos xDD

Por IG pls: [@mapacheverdugo](https://instagram.com/mapacheverdugo)

2023-09-11 20:18 UTC, Im-Fran commented
@mapacheverdugo te acabo de enviar un mensaje por ig, no me deja enviar más hasta que me apruebes la solicitud xD

2023-09-12 01:00 UTC, mapacheverdugo requested changes
Yap, creo que deberíamos tener dos endpoints para las dos funciones de este servicio:

- `GET` `/beca-alimentacion`: para obtener un arreglo de los códigos generados con su fecha correspondiente, en caso de no haber códigos pero sí tener la beca, devolver un arreglo vacio
- `POST` `/beca-alimentacion`: para generar nuevos código de alimentación, que reciba una fecha de inicio y otra de término como parámetro, e idealmente, por buenas prácticas, que devuelva únicamente un arreglo de los cupones generados (si tenía 3 generados, y genero 2 más, me devolverá solo los dos que generé y no los 5 totales que tengo ahora)

2023-09-12 01:00 UTC, mapacheverdugo commented on src/core/routes/academia.routes.ts
> +    "/academia/beca_alimentacion",
Es recomendable usar guiones altos para las URIs. Por otro lado el nombre de la ruta debería estar enfocado en la colección de datos que estás trayendo, no en la plataforma. En este caso que el endpoint se llamara `/beca-alimentacion` sería suficiente, también habría que cambiar el nombre del archivo

2023-09-12 01:00 UTC, mapacheverdugo commented on src/academia/services/beca-alimentacion.service.ts
> +      throw GenericError.FUERA_DE_HORARIO_BECA_ALIMENTACION // Si al generar codigo, no aparece nada, significa que estamos fuera de horario.
Me arrojó este error desde la API cuando no tenías cupones, pero desde la web si pude crearlo

2023-09-12 01:00 UTC, mapacheverdugo commented on src/academia/services/beca-alimentacion.service.ts
> +    // Generar codigo
Creo que este código debería estar separado, en una función para generar códigos y otro para obtenerlos

2023-09-12 01:00 UTC, mapacheverdugo commented on src/academia/services/beca-alimentacion.service.ts
> +    const codigo = $('#datatable > tbody > tr > td:nth-child(1)').text()
No estás considerando la posibilidad de tener más de un código generado, por otro lado tampoco estás devolviendo la fecha del cupón, el cual podría ser un dato relevante para tener.

Cuando tienes más de un cupón el endpoint me devuelve una concatenación de los dos códigos:
```js
{
    "codigo": "4XWXXXXXXX3N1XXXXXXX" // Censurado por si acaso xd
}
```

2023-09-12 01:02 UTC, mapacheverdugo commented on src/academia/services/beca-alimentacion.service.ts
> +    const codigo = $('#datatable > tbody > tr > td:nth-child(1)').text()
Ah, idealmente la fecha convertirla a formato ISO `YYYY-MM-DD`

2023-09-12 01:10 UTC, mapacheverdugo commented
Por cierto, con tu cuenta no hay problema para loggear en Academia

2023-09-12 10:43 UTC, Im-Fran commented on src/academia/services/beca-alimentacion.service.ts
> +      throw GenericError.FUERA_DE_HORARIO_BECA_ALIMENTACION // Si al generar codigo, no aparece nada, significa que estamos fuera de horario.
hmm, que raro, lo revisaré

2023-09-12 10:44 UTC, Im-Fran commented on src/core/routes/academia.routes.ts
> +    "/academia/beca_alimentacion",
buena idea, lo arreglaré :p

2023-09-12 10:45 UTC, Im-Fran commented on src/academia/services/beca-alimentacion.service.ts
> +    const codigo = $('#datatable > tbody > tr > td:nth-child(1)').text()
no sabía que puedes generar más de uno xDD, tipo cuando intento generarlos me sale "ya tienes un cupon generado"

2023-09-12 10:45 UTC, Im-Fran commented
Buena, quizá es esa cuenta de ese desarrollador en especifico? Tendría que verificar

2023-09-12 15:32 UTC, Im-Fran commented
Listop, resolví todo lo que pediste :p

2023-09-16 15:09 UTC, mapacheverdugo requested changes
Yo quitaría la validación de sábado y domingo, ya que en caso de que en el rango de fechas haya un día sábado o domingo el código funciona igual, simplemente no genera ese cupón y por lo tanto no lo devuelve en el array, así que eso ta weno.

La otra opción sería dejar la condición de la siguiente forma:
- Si todos los días del rango de fechas son sábado y/o domingo, devuelve el error
- Si en el rango hay sábado y/o domingo, pero también hay días válidos, crea y devuelve únicamente los cupones válidos (este punto ya lo hace)
- Si todos los días son válidos (no sábado ni domingo), los genera normalmente (este punto igual lo hace)

2023-09-16 15:09 UTC, mapacheverdugo commented on src/core/controllers/beca-alimentacion.controller.ts
> +      if ([0,6].includes(dayjs().tz('America/Santiago').day())) {
Esta condición hace que yo no pueda generar códigos si es sábado o domingo, pero la limitación debería ser que si la fecha del cupón es para un sábado o domingo no se pueda generar ese código

2023-09-16 15:09 UTC, mapacheverdugo commented on src/core/controllers/beca-alimentacion.controller.ts
> +      const hasta = req.body.hasta || dayjs().tz('America/Santiago').add(7, 'day').format('DD-MM-YYYY');
Además del formato, dejaría el default igual que el `desde`, para que genere código de un día y no de 7 días

2023-09-16 15:09 UTC, mapacheverdugo commented on src/core/controllers/beca-alimentacion.controller.ts
> +      const desde = req.body.desde || dayjs().tz('America/Santiago').format('DD-MM-YYYY');
Por consistencia el formato de entrada igual lo dejaría en ISO `YYYY-MM-DD`

2023-09-17 16:36 UTC, Im-Fran commented
Oki, arreglaré todos los comentarios 😉

2023-09-24 19:41 UTC, mapacheverdugo approved these changes
Funciona super, arregla los conflictos no más para poder mergear

2023-10-09 19:15 UTC, merged